<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api\V1;

use App\Http\Resources\UserResource;
use App\Mail\PasskeyNotificationMail;
use App\Models\User;
use App\Support\ApiResponse;
use Illuminate\Auth\SessionGuard;
use Illuminate\Contracts\Support\Responsable;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Mail;
use Laragear\WebAuthn\Http\Requests\AssertedRequest;
use Laragear\WebAuthn\Http\Requests\AssertionRequest;
use Laragear\WebAuthn\Http\Requests\AttestationRequest;
use Laragear\WebAuthn\Http\Requests\AttestedRequest;

/**
 * WebAuthn API controller for the frontend (Next.js PWA).
 *
 * Registration endpoints require auth:sanctum (user must be logged in).
 * Login endpoints are public (passkey = passwordless).
 */
final class WebAuthnApiController
{
    // ── Registration (attestation) ─────────────────────────────────────────

    /**
     * Return creation options (challenge) for passkey registration.
     */
    public function registerOptions(AttestationRequest $request): Responsable
    {
        return $request
            ->fastRegistration()
            ->toCreate();
    }

    /**
     * Verify and store a new passkey credential.
     */
    public function register(AttestedRequest $request): Response
    {
        $request->save($request->filled('alias')
            ? ['alias' => $request->input('alias')]
            : []
        );

        /** @var User $user */
        $user = $request->user();
        $alias = $request->input('alias', 'Mon appareil');

        Mail::to($user)->send(new PasskeyNotificationMail(
            user: $user,
            action: 'added',
            deviceName: $alias,
            ipAddress: $request->ip() ?? '',
            userAgent: $request->userAgent() ?? '',
        ));

        return response()->noContent();
    }

    // ── Login (assertion) ──────────────────────────────────────────────────

    /**
     * Return assertion options (challenge) for passkey login.
     *
     * Since login is unauthenticated, a random token is generated by
     * CacheChallengeRepository and attached as X-WebAuthn-Token header.
     * The frontend must send this token back in the login POST request.
     */
    public function loginOptions(AssertionRequest $request): JsonResponse
    {
        $responsable = $request->toVerify();
        $response = $responsable->toResponse($request);
        $options = json_decode((string) $response->getContent(), true);

        // The token was set on the global request() by CacheChallengeRepository::store(),
        // NOT on $request (which is a FormRequest with its own attributes bag).
        $challengeToken = request()->attributes->get('webauthn_challenge_token', '');

        return response()->json($options)
            ->header('X-WebAuthn-Token', $challengeToken);
    }

    /**
     * Verify a passkey assertion and return a Sanctum token.
     *
     * We cannot use `$request->login()` because it relies on the session guard
     * (Auth::attempt + session regenerate) which doesn't work in a stateless API
     * context. Instead, we use `Auth::guard('web')->validate()` which runs the
     * WebAuthnUserProvider credential check (challenge + signature verification)
     * without needing a session, then issue a Sanctum token manually.
     */
    public function login(AssertedRequest $request): JsonResponse
    {
        $credentials = $request->validated();

        /** @var SessionGuard $guard */
        $guard = auth()->guard('web');

        // validate() calls WebAuthnUserProvider::retrieveByCredentials() + validateCredentials()
        // which verifies the assertion (challenge, signature, counter) without starting a session.
        if (!$guard->validate($credentials)) {
            return ApiResponse::error('Authentification par passkey échouée.', 401);
        }

        // Retrieve the authenticated user (already fetched internally by validate)
        $user = $guard->getLastAttempted();

        if (!$user instanceof User) {
            return ApiResponse::error('Authentification par passkey échouée.', 401);
        }

        $loginContext = $request->input('login_context', 'client');
        $tokenName = $loginContext === 'owner' ? 'owner_passkey_token' : 'client_passkey_token';
        $token = $user->createToken($tokenName)->plainTextToken;

        return response()->json([
            'message' => 'Connexion réussie via passkey.',
            'access_token' => $token,
            'token_type' => 'Bearer',
            'user' => new UserResource($user),
        ]);
    }

    // ── Credential management ──────────────────────────────────────────────

    /**
     * List the authenticated user's passkeys.
     */
    public function index(Request $request): JsonResponse
    {
        /** @var User $user */
        $user = $request->user();

        $credentials = $user->webAuthnCredentials()
            ->select(['id', 'alias', 'origin', 'aaguid', 'created_at', 'updated_at', 'disabled_at'])
            ->orderByDesc('created_at')
            ->get()
            ->map(fn ($c) => [
                'id' => $c->id,
                'alias' => $c->alias,
                'origin' => $c->origin,
                'created_at' => $c->created_at->toIso8601String(),
                'last_used' => $c->updated_at->toIso8601String(),
                'disabled' => $c->disabled_at !== null,
            ]);

        return response()->json(['data' => $credentials]);
    }

    /**
     * Update a passkey's alias.
     */
    public function update(Request $request, string $credentialId): JsonResponse
    {
        $request->validate(['alias' => 'required|string|max:255']);

        /** @var User $user */
        $user = $request->user();

        $credential = $user->webAuthnCredentials()->where('id', $credentialId)->first();

        if (!$credential) {
            return ApiResponse::error('Passkey introuvable.', 404);
        }

        $credential->alias = $request->input('alias');
        $credential->save();

        return response()->json(['message' => 'Passkey renommée.']);
    }

    /**
     * Delete a passkey credential.
     */
    public function destroy(Request $request, string $credentialId): Response
    {
        /** @var User $user */
        $user = $request->user();

        $credential = $user->webAuthnCredentials()->where('id', $credentialId)->first();

        if (!$credential) {
            abort(404, 'Passkey introuvable.');
        }

        $alias = $credential->alias ?? 'Passkey';
        $credential->delete();

        Mail::to($user)->send(new PasskeyNotificationMail(
            user: $user,
            action: 'removed',
            deviceName: $alias,
            ipAddress: $request->ip() ?? '',
            userAgent: $request->userAgent() ?? '',
        ));

        return response()->noContent();
    }
}
