<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api\V1\User;

use App\Exceptions\RoleContextMismatchException;
use App\Http\Requests\Api\V1\User\UpdatePasskeyRequest;
use App\Http\Resources\UserResource;
use App\Mail\PasskeyNotificationMail;
use App\Models\User;
use App\Services\Auth\LoginService;
use App\Support\ApiResponse;
use App\Support\AuthError;
use Illuminate\Auth\SessionGuard;
use Illuminate\Contracts\Support\Responsable;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Laragear\WebAuthn\Http\Requests\AssertedRequest;
use Laragear\WebAuthn\Http\Requests\AssertionRequest;
use Laragear\WebAuthn\Http\Requests\AttestationRequest;
use Laragear\WebAuthn\Http\Requests\AttestedRequest;

/**
 * WebAuthn API controller for the frontend (Next.js PWA).
 *
 * Registration endpoints require auth:sanctum (user must be logged in).
 * Login endpoints are public (passkey = passwordless).
 */
final readonly class WebAuthnApiController
{
    public function __construct(
        private LoginService $loginService,
    ) {}

    // ── Registration (attestation) ─────────────────────────────────────────

    /**
     * Return creation options (challenge) for passkey registration.
     */
    public function registerOptions(AttestationRequest $request): Responsable
    {
        return $request
            ->fastRegistration()
            ->toCreate();
    }

    /**
     * Verify and store a new passkey credential.
     */
    public function register(AttestedRequest $request): Response
    {
        $request->save($request->filled('alias')
            ? ['alias' => $request->input('alias')]
            : []
        );

        /** @var User $user */
        $user = $request->user();
        $alias = $request->input('alias', 'Mon appareil');

        Mail::to($user)->send(new PasskeyNotificationMail(
            user: $user,
            action: 'added',
            deviceName: $alias,
            ipAddress: $request->ip() ?? '',
            userAgent: $request->userAgent() ?? '',
        ));

        return response()->noContent();
    }

    // ── Login (assertion) ──────────────────────────────────────────────────

    /**
     * Return assertion options (challenge) for passkey login.
     *
     * Since login is unauthenticated, a random token is generated by
     * CacheChallengeRepository and attached as X-WebAuthn-Token header.
     * The frontend must send this token back in the login POST request.
     */
    public function loginOptions(AssertionRequest $request): JsonResponse
    {
        $responsable = $request->toVerify();
        $response = $responsable->toResponse($request);
        /** @var array<string,mixed> $options */
        $options = (array) json_decode((string) $response->getContent(), true);

        // The token was set on the global request() by CacheChallengeRepository::store(),
        // NOT on $request (which is a FormRequest with its own attributes bag).
        $challengeToken = (string) request()->attributes->get('webauthn_challenge_token', '');

        // Embed the token in the body under a private `_wt` key as a failsafe.
        // Some reverse proxies / CDN edges (Cloudflare Workers, Vercel Edge) strip
        // custom response headers, making the X-WebAuthn-Token inaccessible to JS.
        // The browser WebAuthn API ignores unknown fields in PublicKeyCredentialRequestOptions,
        // so this does not break the credential.get() call.
        if ($challengeToken !== '') {
            $options['_wt'] = $challengeToken;
        }

        return response()->json($options)
            ->header('X-WebAuthn-Token', $challengeToken);
    }

    /**
     * Verify a passkey assertion and return a Sanctum token.
     *
     * We cannot use `$request->login()` because it relies on the session guard
     * (Auth::attempt + session regenerate) which doesn't work in a stateless API
     * context. Instead, we use `Auth::guard('web')->validate()` which runs the
     * WebAuthnUserProvider credential check (challenge + signature verification)
     * without needing a session, then issue a Sanctum token manually.
     */
    public function login(AssertedRequest $request): JsonResponse
    {
        try {
            $credentials = $request->validated();

            /** @var SessionGuard $guard */
            $guard = auth()->guard('web');

            // validate() calls WebAuthnUserProvider::retrieveByCredentials() + validateCredentials()
            // which verifies the assertion (challenge, signature, counter) without starting a session.
            if (!$guard->validate($credentials)) {
                return ApiResponse::error('Authentification par passkey échouée.', 401);
            }

            // Retrieve the authenticated user (already fetched internally by validate)
            $user = $guard->getLastAttempted();

            if (!$user instanceof User) {
                return ApiResponse::error('Authentification par passkey échouée.', 401);
            }

            $loginContext = $request->input('login_context', 'client');
            if (!in_array($loginContext, ['owner', 'client'], true)) {
                return ApiResponse::error('Contexte de connexion invalide.', 422);
            }

            try {
                $newToken = $this->loginService->issueApiTokenForLoginContext($user, $loginContext);
            } catch (RoleContextMismatchException $e) {
                return AuthError::loginPanelMismatch(code: $e->authCode);
            }

            // Set the verified user on the guard so $request->user() is populated
            // when UserResource is built — this ensures 'role' and 'type' fields
            // are included (they're gated on $request->user()?->id === $this->id).
            auth()->guard('web')->setUser($user);

            Log::debug('[WebAuthn API] login success', [
                'user' => $user->id,
                'email' => $user->email,
                'role' => $user->role->value,
                'login_context' => $loginContext,
            ]);

            return response()->json([
                'message' => 'Connexion réussie via passkey.',
                'access_token' => $newToken->plainTextToken,
                'token_type' => 'Bearer',
                'expires_at' => $newToken->accessToken->expires_at,
                'user' => new UserResource($user),
            ]);
        } catch (\Throwable $e) {
            Log::warning('Passkey API login failed', [
                'error' => $e->getMessage(),
                'credential_id' => $request->input('id'),
                'ip' => $request->ip(),
            ]);

            return ApiResponse::error('Authentification par passkey échouée.', 401);
        }
    }

    // ── Credential management ──────────────────────────────────────────────

    /**
     * List the authenticated user's passkeys.
     */
    public function index(Request $request): JsonResponse
    {
        /** @var User $user */
        $user = $request->user();

        $credentials = $user->webAuthnCredentials()
            ->select(['id', 'alias', 'origin', 'aaguid', 'created_at', 'updated_at', 'disabled_at'])
            ->orderByDesc('created_at')
            ->get()
            ->map(fn ($c) => [
                'id' => $c->id,
                'alias' => $c->alias,
                'origin' => $c->origin,
                'created_at' => $c->created_at->toIso8601String(),
                'last_used' => $c->updated_at->toIso8601String(),
                'disabled' => $c->disabled_at !== null,
            ]);

        return response()->json(['data' => $credentials]);
    }

    /**
     * Update a passkey's alias.
     */
    public function update(UpdatePasskeyRequest $request, string $credentialId): JsonResponse
    {
        /** @var User $user */
        $user = $request->user();

        $credential = $user->webAuthnCredentials()->where('id', $credentialId)->first();

        if (!$credential) {
            return ApiResponse::error('Passkey introuvable.', 404);
        }

        $credential->alias = $request->input('alias');
        $credential->save();

        return response()->json(['message' => 'Passkey renommée.']);
    }

    /**
     * Delete a passkey credential.
     */
    public function destroy(Request $request, string $credentialId): Response
    {
        /** @var User $user */
        $user = $request->user();

        $credential = $user->webAuthnCredentials()->where('id', $credentialId)->first();

        if (!$credential) {
            abort(404, 'Passkey introuvable.');
        }

        $alias = $credential->alias ?? 'Passkey';
        $credential->delete();

        Mail::to($user)->send(new PasskeyNotificationMail(
            user: $user,
            action: 'removed',
            deviceName: $alias,
            ipAddress: $request->ip() ?? '',
            userAgent: $request->userAgent() ?? '',
        ));

        return response()->noContent();
    }
}
