<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Hardening of the e-signature flow (security audit 2026-05-10):
 *
 *   - `pdf_hash_at_request` — sha256 of the contract PDF captured when the
 *      signature request is created. Compared at sign time to detect any
 *      PDF mutation between request and signature (anti-substitution).
 *   - `sign_otp_attempts`  — failed OTP attempts counter; resets when a new
 *      OTP is issued, locks the request when it reaches the lockout cap.
 *   - `signer_ip` / `signer_user_agent` — non-repudiation audit trail
 *      captured at sign / decline time. Required for legal evidence value.
 *
 *  The existing `signature_hash` column keeps its original semantics ("sha256
 *  of signed PDF at sign time") — code now actually populates it.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('lease_signature_requests', function (Blueprint $table): void {
            $table->string('pdf_hash_at_request', 64)
                ->nullable()
                ->after('signature_hash');

            $table->unsignedSmallInteger('sign_otp_attempts')
                ->default(0)
                ->after('sign_otp_sent_at');

            $table->string('signer_ip', 45)->nullable()->after('declined_at');
            $table->string('signer_user_agent', 512)->nullable()->after('signer_ip');
        });

        // Extend the Postgres CHECK constraint generated by `enum()` so the
        // new `locked` status (set by `registerOtpFailure()` and the
        // anti-substitution guard) is accepted at the DB level.
        if (DB::connection()->getDriverName() === 'pgsql') {
            DB::statement('ALTER TABLE lease_signature_requests DROP CONSTRAINT IF EXISTS lease_signature_requests_status_check');
            DB::statement(<<<'SQL'
                ALTER TABLE lease_signature_requests
                ADD CONSTRAINT lease_signature_requests_status_check
                CHECK (status IN ('pending', 'viewed', 'signed', 'declined', 'expired', 'locked'))
            SQL);
        }
    }

    public function down(): void
    {
        Schema::table('lease_signature_requests', function (Blueprint $table): void {
            $table->dropColumn([
                'pdf_hash_at_request',
                'sign_otp_attempts',
                'signer_ip',
                'signer_user_agent',
            ]);
        });
    }
};
