<?php

declare(strict_types=1);

namespace App\Support;

final class PropertyAttributeCatalog
{
    /**
     * @return array<int, array{
     *     name: string,
     *     icon: string,
     *     admin_icon: string,
     *     attributes: array<int, array{name: string, icon?: string, admin_icon?: string}>
     * }>
     */
    public static function categories(): array
    {
        return [
            [
                'name' => 'Salle de bain',
                'icon' => 'Bathtub',
                'admin_icon' => 'heroicon-o-beaker',
                'attributes' => [
                    ['name' => 'Produits de nettoyage', 'icon' => 'CleaningServices'],
                    ['name' => 'Savon pour le corps', 'icon' => 'Soap'],
                    ['name' => 'Eau chaude', 'icon' => 'HotTub'],
                    ['name' => 'Baignoire', 'icon' => 'Bathtub'],
                    ['name' => 'Douche', 'icon' => 'Shower'],
                    ['name' => 'Cabine de douche séparée', 'icon' => 'Shower'],
                    ['name' => 'Sèche-cheveux', 'icon' => 'Dry'],
                    ['name' => 'Serviettes de bain', 'icon' => 'Checkroom'],
                    ['name' => 'Gel douche', 'icon' => 'Soap'],
                    ['name' => 'Shampoing', 'icon' => 'Spa'],
                    ['name' => 'Conditionneur', 'icon' => 'Spa'],
                    ['name' => 'Papier toilette', 'icon' => 'LocalOffer'],
                    ['name' => 'Miroir', 'icon' => 'CropSquare'],
                    ['name' => 'Pèse-personne', 'icon' => 'MonitorWeight'],
                ],
            ],
            [
                'name' => 'Chambre et linge',
                'icon' => 'Bed',
                'admin_icon' => 'heroicon-o-moon',
                'attributes' => [
                    ['name' => 'Linge de lit', 'icon' => 'Bed'],
                    ['name' => 'Draps et taies d\'oreiller', 'icon' => 'KingBed'],
                    ['name' => 'Oreillers', 'icon' => 'AirlineSeatIndividualSuite'],
                    ['name' => 'Couvertures', 'icon' => 'Layers'],
                    ['name' => 'Couette', 'icon' => 'Bed'],
                    ['name' => 'Cintres', 'icon' => 'Checkroom'],
                    ['name' => 'Stores occultants', 'icon' => 'Blinds'],
                    ['name' => 'Fer à repasser', 'icon' => 'Iron'],
                    ['name' => 'Planche à repasser', 'icon' => 'TableBar'],
                    ['name' => 'Armoire / Dressing', 'icon' => 'Wardrobe'],
                    ['name' => 'Lit bébé / Berceau', 'icon' => 'ChildCare'],
                    ['name' => 'Réveil', 'icon' => 'Alarm'],
                    ['name' => 'Coussins décoratifs', 'icon' => 'Chair'],
                ],
            ],
            [
                'name' => 'Cuisine',
                'icon' => 'Kitchen',
                'admin_icon' => 'heroicon-o-cake',
                'attributes' => [
                    ['name' => 'Cuisine équipée', 'icon' => 'Kitchen'],
                    ['name' => 'Réfrigérateur', 'icon' => 'Kitchen'],
                    ['name' => 'Congélateur', 'icon' => 'AcUnit'],
                    ['name' => 'Four', 'icon' => 'Microwave'],
                    ['name' => 'Micro-ondes', 'icon' => 'Microwave'],
                    ['name' => 'Lave-vaisselle', 'icon' => 'LocalDining'],
                    ['name' => 'Cafetière', 'icon' => 'Coffee'],
                    ['name' => 'Machine à expresso', 'icon' => 'CoffeeMaker'],
                    ['name' => 'Bouilloire', 'icon' => 'Kettle'],
                    ['name' => 'Grille-pain', 'icon' => 'LunchDining'],
                    ['name' => 'Mixeur / Blender', 'icon' => 'Blender'],
                    ['name' => 'Ustensiles de cuisine', 'icon' => 'Restaurant'],
                    ['name' => 'Casseroles, poêles, couteaux', 'icon' => 'SoupKitchen'],
                    ['name' => 'Vaisselle', 'icon' => 'DinnerDining'],
                    ['name' => 'Assiettes, verres, couverts', 'icon' => 'RestaurantMenu'],
                    ['name' => 'Plaques de cuisson', 'icon' => 'Skillet'],
                    ['name' => 'Hotte aspirante', 'icon' => 'Air'],
                    ['name' => 'Épices et condiments', 'icon' => 'Science'],
                    ['name' => 'Huile et sel', 'icon' => 'WaterDrop'],
                ],
            ],
            [
                'name' => 'Séjour',
                'icon' => 'Weekend',
                'admin_icon' => 'heroicon-o-home-modern',
                'attributes' => [
                    ['name' => 'Canapé', 'icon' => 'Weekend'],
                    ['name' => 'Canapé-lit', 'icon' => 'Hotel'],
                    ['name' => 'Table à manger', 'icon' => 'TableRestaurant'],
                    ['name' => 'Chaises', 'icon' => 'Chair'],
                    ['name' => 'Bureau', 'icon' => 'Desk'],
                    ['name' => 'Chaise de bureau', 'icon' => 'Chair'],
                    ['name' => 'Bibliothèque', 'icon' => 'MenuBook'],
                    ['name' => 'Jeux de société', 'icon' => 'Casino'],
                    ['name' => 'Livres', 'icon' => 'LibraryBooks'],
                    ['name' => 'Tapis', 'icon' => 'Texture'],
                ],
            ],
            [
                'name' => 'Divertissement',
                'icon' => 'Tv',
                'admin_icon' => 'heroicon-o-tv',
                'attributes' => [
                    ['name' => 'Télévision', 'icon' => 'Tv'],
                    ['name' => 'TV HD', 'icon' => 'Tv'],
                    ['name' => '4K / Full HD', 'icon' => 'HighQuality'],
                    ['name' => 'TV connectée', 'icon' => 'ConnectedTv'],
                    ['name' => 'Netflix, Prime, YouTube', 'icon' => 'Subscriptions'],
                    ['name' => 'Accès Netflix', 'icon' => 'LiveTv'],
                    ['name' => 'Accès Spotify', 'icon' => 'GraphicEq'],
                    ['name' => 'Enceinte Bluetooth', 'icon' => 'Speaker'],
                    ['name' => 'Console de jeux', 'icon' => 'SportsEsports'],
                    ['name' => 'PS5, Xbox, Nintendo Switch', 'icon' => 'SportsEsports'],
                    ['name' => 'Projecteur', 'icon' => 'Videocam'],
                    ['name' => 'Lecteur DVD / Blu-Ray', 'icon' => 'Album'],
                    ['name' => 'Vinyl / Tourne-disque', 'icon' => 'Album'],
                ],
            ],
            [
                'name' => 'Connectivité',
                'icon' => 'Wifi',
                'admin_icon' => 'heroicon-o-wifi',
                'attributes' => [
                    ['name' => 'WiFi', 'icon' => 'Wifi'],
                    ['name' => 'WiFi haut débit', 'icon' => 'NetworkWifi'],
                    ['name' => '+100 Mb/s', 'icon' => 'Speed'],
                    ['name' => 'WiFi fibre', 'icon' => 'Router'],
                    ['name' => 'Ethernet / Port réseau', 'icon' => 'Lan'],
                    ['name' => 'Espace de travail dédié', 'icon' => 'Work'],
                    ['name' => 'Imprimante', 'icon' => 'Print'],
                ],
            ],
            [
                'name' => 'Climatisation et chauffage',
                'icon' => 'Thermostat',
                'admin_icon' => 'heroicon-o-fire',
                'attributes' => [
                    ['name' => 'Climatisation', 'icon' => 'AcUnit'],
                    ['name' => 'Climatisation réversible', 'icon' => 'SyncAlt'],
                    ['name' => 'Chaud et froid', 'icon' => 'DeviceThermostat'],
                    ['name' => 'Chauffage central', 'icon' => 'Whatshot'],
                    ['name' => 'Radiateurs électriques', 'icon' => 'ElectricalServices'],
                    ['name' => 'Cheminée', 'icon' => 'Fireplace'],
                    ['name' => 'Poêle à bois', 'icon' => 'LocalFireDepartment'],
                    ['name' => 'Ventilateur', 'icon' => 'ModeFanOff'],
                    ['name' => 'Thermostat', 'icon' => 'Thermostat'],
                ],
            ],
            [
                'name' => 'Sécurité',
                'icon' => 'Security',
                'admin_icon' => 'heroicon-o-shield-check',
                'attributes' => [
                    ['name' => 'Détecteur de fumée', 'icon' => 'Sensors'],
                    ['name' => 'Détecteur de CO', 'icon' => 'Air'],
                    ['name' => 'Monoxyde de carbone', 'icon' => 'WarningAmber'],
                    ['name' => 'Extincteur', 'icon' => 'LocalFireDepartment'],
                    ['name' => 'Trousse de premiers secours', 'icon' => 'MedicalServices'],
                    ['name' => 'Coffre-fort', 'icon' => 'Lock'],
                    ['name' => 'Serrure connectée', 'icon' => 'LockClock'],
                    ['name' => 'Interphone / Visiophone', 'icon' => 'VideoCall'],
                    ['name' => 'Caméra de sécurité', 'icon' => 'Videocam'],
                    ['name' => 'Extérieur uniquement', 'icon' => 'Landscape'],
                    ['name' => 'Alarme', 'icon' => 'NotificationImportant'],
                    ['name' => 'Gardien / Concierge', 'icon' => 'SupportAgent'],
                ],
            ],
            [
                'name' => 'Extérieur',
                'icon' => 'Deck',
                'admin_icon' => 'heroicon-o-sun',
                'attributes' => [
                    ['name' => 'Terrasse', 'icon' => 'Deck'],
                    ['name' => 'Balcon', 'icon' => 'Balcony'],
                    ['name' => 'Jardin privatif', 'icon' => 'Yard'],
                    ['name' => 'Jardin commun', 'icon' => 'Park'],
                    ['name' => 'Barbecue', 'icon' => 'OutdoorGrill'],
                    ['name' => 'Mobilier de jardin', 'icon' => 'ChairAlt'],
                    ['name' => 'Piscine privée', 'icon' => 'Pool'],
                    ['name' => 'Piscine commune', 'icon' => 'Pool'],
                    ['name' => 'Jacuzzi', 'icon' => 'HotTub'],
                    ['name' => 'Sauna', 'icon' => 'Spa'],
                    ['name' => 'Vue sur mer', 'icon' => 'Water'],
                    ['name' => 'Vue sur montagne', 'icon' => 'Landscape'],
                    ['name' => 'Vue sur jardin', 'icon' => 'Nature'],
                    ['name' => 'Accès plage', 'icon' => 'BeachAccess'],
                ],
            ],
            [
                'name' => 'Stationnement et accès',
                'icon' => 'DirectionsCar',
                'admin_icon' => 'heroicon-o-truck',
                'attributes' => [
                    ['name' => 'Parking privé', 'icon' => 'LocalParking'],
                    ['name' => 'Parking gratuit', 'icon' => 'LocalParking'],
                    ['name' => 'Dans la rue', 'icon' => 'AddRoad'],
                    ['name' => 'Parking payant', 'icon' => 'Paid'],
                    ['name' => 'Garage', 'icon' => 'Garage'],
                    ['name' => 'Place de vélo', 'icon' => 'PedalBike'],
                    ['name' => 'Borne de recharge VE', 'icon' => 'EvStation'],
                    ['name' => 'Véhicule électrique', 'icon' => 'ElectricCar'],
                    ['name' => 'Ascenseur', 'icon' => 'Elevator'],
                    ['name' => 'Accès PMR', 'icon' => 'Accessible'],
                    ['name' => 'Personnes à mobilité réduite', 'icon' => 'AccessibleForward'],
                    ['name' => 'Entrée privée', 'icon' => 'MeetingRoom'],
                    ['name' => 'Digicode / Badge', 'icon' => 'Pin'],
                ],
            ],
            [
                'name' => 'Buanderie',
                'icon' => 'LocalLaundryService',
                'admin_icon' => 'heroicon-o-archive-box',
                'attributes' => [
                    ['name' => 'Lave-linge', 'icon' => 'LocalLaundryService'],
                    ['name' => 'Sèche-linge', 'icon' => 'DryCleaning'],
                    ['name' => 'Lessive fournie', 'icon' => 'CleaningServices'],
                    ['name' => 'Étendoir à linge', 'icon' => 'Dry'],
                    ['name' => 'Buanderie commune', 'icon' => 'LocalLaundryService'],
                ],
            ],
            [
                'name' => 'Animaux et famille',
                'icon' => 'FamilyRestroom',
                'admin_icon' => 'heroicon-o-heart',
                'attributes' => [
                    ['name' => 'Animaux acceptés', 'icon' => 'Pets'],
                    ['name' => 'Lit bébé disponible', 'icon' => 'ChildCare'],
                    ['name' => 'Chaise haute', 'icon' => 'Chair'],
                    ['name' => 'Baignoire bébé', 'icon' => 'Bathtub'],
                    ['name' => 'Jouets enfants', 'icon' => 'Toys'],
                    ['name' => 'Aire de jeux', 'icon' => 'SportsSoccer'],
                ],
            ],
        ];
    }
}
